# This workflow will run when a pull request is made

name: Nightly-Regression

on:
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:

  nightly-regression:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running nightly regression suite
        run: python ./tests/turnin.py
